package radiobuttondemo;

import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

public class RadioButtonDemo implements ItemListener {
	JLabel jlabOptions, jlabWhat;   
	JRadioButton jrbSpeed, jrbSize, jrbDebug; 
	JCheckBox jcbOptions;
	
	RadioButtonDemo(){
		JFrame jfrm = new JFrame("Demonstrate Radio Buttons");  
		  
	    // Specify a 1 column, 6 row grid layout. 
	    jfrm.setLayout(new GridLayout(6, 1)); 
	    jfrm.setSize(300, 150);  
	    jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  

	    jlabOptions = new JLabel("Choose Options: ");  
	    jlabWhat = new JLabel("Options selected: Speed");  
	  
	    jcbOptions = new JCheckBox("Enable Options"); 
	    
	    jrbSpeed = new JRadioButton("Maximize Speed",true);  
	    jrbSize = new JRadioButton("Minimize Size");  
	    jrbDebug = new JRadioButton("Debug");  
	    
	    // Add radio buttons to a group. 
	    ButtonGroup bg = new ButtonGroup(); 
	    bg.add(jrbSpeed); 
	    bg.add(jrbSize); 
	    bg.add(jrbDebug); 
	 
	    // Initially disable option check boxes. 
	    jrbSpeed.setEnabled(false); 
	    jrbSize.setEnabled(false); 
	    jrbDebug.setEnabled(false); 
	    
	    // Add item listener for jcbOptions. 
	    jcbOptions.addItemListener(new ItemListener() {
	    	public void itemStateChanged(ItemEvent ie){
	    		if(jcbOptions.isSelected()) { 
	  	          jrbSpeed.setEnabled(true); 
	  	          jrbSize.setEnabled(true); 
	  	          jrbDebug.setEnabled(true); 
	  	        } else { 
	  	          jrbSpeed.setEnabled(false); 
	  	          jrbSize.setEnabled(false); 
	  	          jrbDebug.setEnabled(false); 
	  	        } 
	    	}	
	    });
	    
	    // Events generated by the Options check boxes are handled in common by the itemStateChanged() method. 
	    jrbSpeed.addItemListener(this); 
	    jrbSize.addItemListener(this); 
	    jrbDebug.addItemListener(this); 
	    
	    jfrm.add(jcbOptions);   
	    jfrm.add(jlabOptions);  
	 
	    jfrm.add(jrbSpeed);   
	    jfrm.add(jrbSize);   
	    jfrm.add(jrbDebug);   
	    jfrm.add(jlabWhat);  
	    
	    jfrm.setVisible(true);  
	    	
	}
	
	public void itemStateChanged(ItemEvent ie){
		String opts = ""; 
		
		// Build a string that contains all selected options. 
	    if(jrbSpeed.isSelected()) {
	    	opts = "Speed "; 
	    }else if(jrbSize.isSelected()){
	    	opts = "Size "; 
	    }else{
	    	opts = "Debug "; 
	    }

	    // Display the currently selected options. 
	    jlabWhat.setText("Options selected: " + opts); 
	}
	 

}
