package checkboxDemo;

import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class CheckboxDemo implements ItemListener {
	JLabel jlabOptions, jlabWhat, jlabChange;   
	JCheckBox jcbOptions, jcbSpeed, jcbSize, jcbDebug; 
	
	CheckboxDemo(){
		JFrame jfrm = new JFrame("Demonstrate Check Boxes");  
		  
	    // Specify a 1 column, 7 row grid layout. 
	    jfrm.setLayout(new GridLayout(7, 1)); 
	    jfrm.setSize(300, 150);  
	    jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  

	    jlabOptions = new JLabel("Options: ");  
	    jlabChange = new JLabel("");  
	    jlabWhat = new JLabel("Options selected: ");  
	  
	    // Make check boxes. 
	    jcbOptions = new JCheckBox("Enable Options");  
	    jcbSpeed = new JCheckBox("Maximize Speed");  
	    jcbSize = new JCheckBox("Minimize Size");  
	    jcbDebug = new JCheckBox("Debug");  
	 
	    // Initially disable option check boxes. 
	    jcbSpeed.setEnabled(false); 
	    jcbSize.setEnabled(false); 
	    jcbDebug.setEnabled(false); 
	    
	    // Add item listener for jcbOptions. 
	    jcbOptions.addItemListener(new ItemListener() {
	    	public void itemStateChanged(ItemEvent ie){
	    		if(jcbOptions.isSelected()) { 
	  	          jcbSpeed.setEnabled(true); 
	  	          jcbSize.setEnabled(true); 
	  	          jcbDebug.setEnabled(true); 
	  	        } else { 
	  	          jcbSpeed.setEnabled(false); 
	  	          jcbSize.setEnabled(false); 
	  	          jcbDebug.setEnabled(false); 
	  	        } 
	    	}	
	    });
	    
	    // Events generated by the Options check boxes are handled in common by the itemStateChanged() method. 
	    jcbSpeed.addItemListener(this); 
	    jcbSize.addItemListener(this); 
	    jcbDebug.addItemListener(this); 
	    
	    jfrm.add(jcbOptions);   
	    jfrm.add(jlabOptions);  
	 
	    jfrm.add(jcbSpeed);   
	    jfrm.add(jcbSize);   
	    jfrm.add(jcbDebug);   
	    jfrm.add(jlabChange);  
	    jfrm.add(jlabWhat);  
	    
	    jfrm.setVisible(true);  
	    	
	}
	
	public void itemStateChanged(ItemEvent ie){
		String opts = ""; 
		 
	    // Obtain a reference to the check box that caused the event. 
	    JCheckBox cb = (JCheckBox) ie.getItem();
	    
	    // Tell the user what they did. 
	    if(ie.getStateChange() == ItemEvent.SELECTED){
	    	jlabChange.setText("Selection change: " + cb.getText() + " selected.");      
	    } else{
	    	jlabChange.setText("Selection change: " + cb.getText() + " cleared."); 
	    }

	    // Build a string that contains all selected options. 
	    if(jcbSpeed.isSelected()) opts += "Speed "; 
	    if(jcbSize.isSelected()) opts += "Size "; 
	    if(jcbDebug.isSelected()) opts += "Debug "; 
	 
	    // Display the currently selected options. 
	    jlabWhat.setText("Options selected: " + opts); 
	}
	 
}
