---
title: "ggplot2 examples"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_depth: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r comment='', warning=FALSE,message=FALSE}
library(ggplot2)
library(reshape2)
data(Oxboys, package = "nlme")
diamonds = na.omit(diamonds)
msleep = na.omit(msleep)
mtcars = na.omit(mtcars)
Oxboys = na.omit(Oxboys)
mpg = na.omit(mpg)
mydata <- mtcars[, c(1,3,4,5,6,7)]
```

# 1. 散点图

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mtcars, aes(x=mpg, y=wt)) + geom_point()
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mtcars, aes(x=mpg, y=wt)) + geom_point(aes(colour = factor(cyl)))
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mtcars, aes(x=mpg, y=wt)) + geom_point(colour = "darkblue")
```


# 2. 柱状图

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mpg, aes(class)) + geom_bar(fill="steelblue",colour="black")
```

# 3. 直方图

```{r comment='', warning=FALSE,message=FALSE}
ggplot(diamonds, aes(carat)) + geom_histogram(bins = 30)
```

# 4. 热图

```{r comment='', warning=FALSE,message=FALSE}
cormat <- round(cor(mydata),2)
melted_cormat <- melt(cormat)
head(melted_cormat)
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(data = melted_cormat, aes(x=Var1, y=Var2)) + geom_raster(aes(fill=value))
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(data = melted_cormat, aes(x=Var1, y=Var2)) + geom_raster(aes(fill=value), interpolate = TRUE)
```

# 5. 箱线图

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mpg, aes(x=class, y=hwy)) + geom_boxplot()
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mpg, aes(x=class, y=hwy)) + geom_boxplot() + geom_jitter(width = 0.2)
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mpg, aes(x=class, y=hwy)) + geom_boxplot() + coord_flip()
```

```{r comment='', warning=FALSE,message=FALSE}
ggplot(mpg, aes(x=class, y=hwy)) + geom_boxplot(outlier.colour = "red", outlier.shape = 1)
```





