---
title: "Visualize Correlation Matrices"
output:
  html_document:
    keep_md: true
---

```{r comment='',message=FALSE,warning=FALSE}
mydata <- mtcars[, c('mpg', 'cyl', 'disp', 'hp', 'carb')]
```

# 1. PerformanceAnalytics Package

```{r comment='',message=FALSE,warning=FALSE}
library("PerformanceAnalytics")
chart.Correlation(mydata, histogram=TRUE, pch=19)
```

# 2. Corrr Package

```{r comment='',message=FALSE,warning=FALSE}
library(corrr)
mydata %>% correlate() %>% network_plot(min_cor=0.6)
````

# 3. Psych Package

```{r comment='',message=FALSE,warning=FALSE}
library(psych)
pairs.panels(mydata, scale=TRUE)
````

# 4. Corrplot Package

```{r comment='',message=FALSE,warning=FALSE}
library(corrplot)
corrplot.mixed(cor(mydata), order="hclust", tl.col="black")
````

# 5. GGally Package

```{r comment='',message=FALSE,warning=FALSE}
library(GGally)
ggpairs(mydata)
````

# 6. ggcorrplot Package

```{r comment='',message=FALSE,warning=FALSE}
library(ggcorrplot)
ggcorrplot(cor(mtcars), p.mat = cor_pmat(mtcars), hc.order=TRUE, type='lower')
````

# Reference

- https://github.com/JamesMarquezDev/Jupyter-Notebooks-Statistic-Walk-Throughs-Using-R/blob/master/correlation_matrices_in_r.ipynb


