import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @Yanhui Fan, nolanfyh@gmail.com
 * Saturday, 27 Oct 2012
 */
public class calculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form calculatorForm
     */
    public calculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNumText = new javax.swing.JTextField();
        secondNumText = new javax.swing.JTextField();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        multipleButton = new javax.swing.JButton();
        devideButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        powerButton = new javax.swing.JButton();
        logEButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        expButton = new javax.swing.JButton();
        answerText = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");

        jLabel1.setText("First Number");

        jLabel2.setText("Second Number");

        plusButton.setText("+");
        plusButton.setToolTipText("add");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setText("-");
        minusButton.setToolTipText("subtract");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        answerLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        answerLabel.setText("The answer is:");

        multipleButton.setText("*");
        multipleButton.setToolTipText("multiple");
        multipleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleButtonActionPerformed(evt);
            }
        });

        devideButton.setText("/");
        devideButton.setToolTipText("divide");
        devideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devideButtonActionPerformed(evt);
            }
        });

        sqrtButton.setText("sqrt");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });

        powerButton.setText("power");
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });

        logEButton.setText("log");
        logEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logEButtonActionPerformed(evt);
            }
        });

        logButton.setText("log10");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        expButton.setText("exp");
        expButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(answerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answerText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(secondNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sqrtButton)
                                .addGap(18, 18, 18)
                                .addComponent(logEButton)
                                .addGap(18, 18, 18)
                                .addComponent(logButton)
                                .addGap(18, 18, 18)
                                .addComponent(expButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plusButton)
                                .addGap(18, 18, 18)
                                .addComponent(minusButton)
                                .addGap(18, 18, 18)
                                .addComponent(multipleButton)
                                .addGap(18, 18, 18)
                                .addComponent(devideButton)
                                .addGap(18, 18, 18)
                                .addComponent(powerButton)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(secondNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusButton)
                    .addComponent(minusButton)
                    .addComponent(multipleButton)
                    .addComponent(devideButton)
                    .addComponent(powerButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqrtButton)
                    .addComponent(logEButton)
                    .addComponent(logButton)
                    .addComponent(expButton))
                .addGap(47, 47, 47)
                .addComponent(answerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(clearButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Double.parseDouble(
                    this.secondNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad second number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 + number2;

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Double.parseDouble(
                    this.secondNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad second number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 - number2;

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_minusButtonActionPerformed

    private void devideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devideButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Double.parseDouble(
                    this.secondNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad second number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 / number2;

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_devideButtonActionPerformed

    private void multipleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Double.parseDouble(
                    this.secondNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad second number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = number1 * number2;

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_multipleButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        double number1;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.secondNumText.setText(null);

        double answer = Math.sqrt(number1);

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerButtonActionPerformed
        double number1, number2;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            number2 = Double.parseDouble(
                    this.secondNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad second number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double answer = Math.pow(number1, number2);

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_powerButtonActionPerformed

    private void logEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logEButtonActionPerformed
        double number1;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.secondNumText.setText(null);

        double answer = Math.log(number1);

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_logEButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        double number1;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.secondNumText.setText(null);

        double answer = Math.log10(number1);

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_logButtonActionPerformed

    private void expButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expButtonActionPerformed
        double number1;
        try {
            number1 = Double.parseDouble(
                    this.firstNumText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad first number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.secondNumText.setText(null);

        double answer = Math.exp(number1);

        NumberFormat f = NumberFormat.getInstance();
        f.setMaximumFractionDigits(4); // 4 digits
        String s = f.format(answer);

        // this.answerLabel.setText("The answer is: "  + s);
        this.answerText.setText(s);
    }//GEN-LAST:event_expButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.firstNumText.setText(null);
        this.secondNumText.setText(null);
        this.answerText.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JTextField answerText;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton devideButton;
    private javax.swing.JButton expButton;
    private javax.swing.JTextField firstNumText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logButton;
    private javax.swing.JButton logEButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multipleButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton powerButton;
    private javax.swing.JTextField secondNumText;
    private javax.swing.JButton sqrtButton;
    // End of variables declaration//GEN-END:variables
}
